name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'PR test'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ x86_64, aarch64 ]
    steps:
      - uses: actions/checkout@v4

      - name: Restore kernel cache
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          name: kernel_cache-${{ matrix.arch }}
          workflow: build.yml
          workflow_conclusion: success
          path: build/kernel
          if_no_artifact_found: ignore

      - name: Add deps
        run: sudo apt update && sudo apt upgrade -y && sudo apt install -y python3-kconfiglib

      - name: Clean
        run: make clean-${{ matrix.arch }}

      - name: Build kpart
        run: make ACTION=1 ${{ matrix.arch }}

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: buildcharge-${{ matrix.arch }}
          path: out

      - name: Clean2
        run: make clean-${{ matrix.arch }}

      - name: Upload kernel cache
        uses: actions/upload-artifact@v4
        with:
          name: kernel_cache-${{ matrix.arch }}
          path: build/kernel
