name: Build Everything & upload (x86_64)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: add deps
      run: sudo apt update && sudo apt upgrade -y
    - name: Build kpart
      run: make x86_64
    - name: Upload build files
      uses: actions/upload-artifact@v4
      with:
        name: kpart-x86_64
        path: out